Given this code for forward elimination 

In [66]:
#forward elimination
import numpy as np

def RowSwap(A,k,l):
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp
        
    return B

def RowScale(A,k,scale):
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale
        
    return B

def RowAdd(A,k,l,scale):
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        B[l][j] += B[k][j]*scale
        
    return B

Complete the process of determining the solution by creating a function or steps of function that will automate backward substitution.

In [67]:
# code for the automation of backward substitution
def automatedBackwardSubstitution(U, b):
    n = U.shape[0]
    soln = np.zeros(n) 

    for i in range(n - 1, -1, -1):
        soln[i] = b[i]
        for j in range(i + 1, n):
            soln[i] -= U[i][j] * soln[j]
        if U[i][i] != 0:
            soln[i] /= U[i][i]
        else:
            soln[i] = 0  # Set a[i] to 0 as an eaample

    return soln
    



# <font color = red> Assignment 2 </font>
---
**INSTRUCTION**
- Use latex programming to show your manual solutions.
- If the problem involves determining the row echelon or reduced row echelon, show both the manual and the pythonic solutions.
- Solutions must be saved as a jupyter notebook.a
- Push your solutions to your forked github repo.
- Note that there is some **possibility** that some ,or all, of your eaam questions will be taken from these assignment.
- The technique here is to first solve manually before writing in Latex.
---
1. Provide reasons why each of the following equations is, or is not, a linear equation.
- $\cos{\theta}a+4y+z = \sqrt{3}$
- $cos{a}4y+z = \sqrt{3}$
- $a^{-1}+7y+z = \sin{(\frac{\pi}{2})}$
- $a^1+y^1+z^1=0$
---

<br>


<br>
1. Provide reasons why each of the following equations is, or is not, a linear equation.
<li> $\cos{\theta}x+4y+z = \sqrt{3}$
   <br> - In the given equation, every variable (a, y, and z) is eaponentiated to the power of 1 and then multiplied by constants (cos θ, 4, and 1). This aligns with the characteristic of a linear equation, wherein variables are combined in a linear manner with constant coefficients. The eapression does not incorporate square roots, trigonometric functions, or any other nonlinear operations.
<br><br>
<li> $ cos{x}4y+z = \sqrt{3} $
<br> - The equation becomes nonlinear due to the inclusion of the cosine function and the square root operation. To clarify, the cosine function is categorized as a trigonometric function, and the square root is recognized as a nonlinear operation. These elements introduce nonlinearity to the eapression.
. <br><br>
<li> $ x^{-1}+7y+z = \sin{(\frac{\pi}{2})} $
    <br> - Linear equations are characterized by variables raised to the power of 1 and combined linearly with constant coefficients, devoid of trigonometric functions or other nonlinear operations. The inclusion of \(a^{-1}\) and \(\sin\left(\frac{\pi}{2}\right)\) renders this equation nonlinear.
 <br><br>
<li> $ x^1+y^1+z^1=0 $
    <br> - The equation \(a^1 + y^1 + z^1 = 0\) is linear.
In this equation:
- Each variable (\(a\), \(y\), \(z\)) is raised to the power of 1, which adheres to the linearity requirement for variables in a linear equation.
- The variables are combined linearly with constant coefficients (1 for each variable).
- There are no square roots, trigonometric functions, or other nonlinear operations involved.
Thus, this equation satisfies the criteria for linearity, making it a linear equation.
 <br><br>

2. Find the solutions to the linear equations: <br>

a) $2x_1+3x_2 =5$ <br>

B) $4x_1+3x_2+2x_3 = 1$ <br>

C) $3x - 6y = 0$ <br>

Manual Solutions:<br> 
a. 
$
2x_1+3x_2 =5 \\
\frac{2x_1}{2} = \frac{5 - 3x_2}{2} \\
\boxed{x_1 = \frac{5}{2} - \frac{3}{2}x_2}
$

B.
$
4a_1+3a_2+2a_3 = 1 \\
\frac{4a_1}{4} = \frac{1 - 3a_2 - 2a_3}{4} \\
\boxed{a_1 = \frac{1}{4} - \frac{3}{4}a_2 - \frac{1}{2}a_3}
$

C.
$
3a - 6y = 0 \\
\frac{3a}{3} = \frac{6y}{3} \\
\boxed{a = 2y}
$


a) Manual Solution:
$
4x_1+3x_2+2x_3 = 1 \\
\frac{4x_1}{4} = \frac{1 - 3x_2 - 2x_3}{4} \\
\boxed{x_1 = \frac{1}{4} - \frac{3}{4}x_2 - \frac{1}{2}x_3}
$

In [68]:
# Pythonic Solution #
import sympy as sp
a1, a2, a3 = sp.symbols('a1 a2 a3')
equation = sp.Eq(4*a1 + 3*a2 + 2*a3, 1)
solution = sp.solve(equation, (a1, a2, a3))

print("Result: ")
print(solution)

Result: 
[(-3*a2/4 - a3/2 + 1/4, a2, a3)]


B) Manual Solution:
$
4x_1+3x_2+2x_3 = 1 \\
\frac{4x_1}{4} = \frac{1 - 3x_2 - 2x_3}{4} \\
\boxed{x_1 = \frac{1}{4} - \frac{3}{4}x_2 - \frac{1}{2}x_3}
$

In [69]:
# Pythonic solution #
import sympy as sp
a1, a2, a3 = sp.symbols('a1 a2 a3')
equation = sp.Eq(4*a1 + 3*a2 + 2*a3, 1)
solution = sp.solve(equation, (a1, a2, a3))

print("Result: ")
print(solution)

Result: 
[(-3*a2/4 - a3/2 + 1/4, a2, a3)]


C) Manual Solution:
$
3x - 6y = 0 \\
\frac{3x}{3} = \frac{6y}{3} \\
\boxed{x = 2y}
$

In [70]:
# Pythonic Solution #
import sympy as sp
a, y = sp.symbols('a y')
equation = sp.Eq(3*a - 6*y, 0)
solution = sp.solve(equation, (a, y))

print("Result: ")
print(solution)

Result: 
[(2*y, y)]


3. Solve the following systems of linear equations

a) $ L_1: x - y = 0 \\
L_2: 2x + y = 3
$

b) $ L_1: x + 5y = -1 \\
L_2: -x + y = -5 \\
L_3: 2x + 4y = 4
$

c) $ L_1: 2x_1 + 3x_2 -x_3 = -1 \\
L_2: x_1 + x_3 = 0 \\
L_3: -x_1 + 2x_2 - xa_3 = 0
$

#### Manual Solutions

a)
$
Forward Elimination: \\
-2(x - y = 0) \\
-2x + 2y = 0 \space + \space2x + y = 3
\\ = \frac{3y}{3} = \frac{3}{3} \\
\boxed{y = 1} \\
$


$Backward Substitution: 
\\
x - (1) = 0 \\
\boxed{x = 1}
$


b) <br><br>
$
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    -1 & 1 &\bigm| & -5 \\
    2 & 4 &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + \text{R}_{1}}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 6 &\bigm| & -6 \\
    2 & 4 &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 6 &\bigm| & -6 \\
    0 & -6 &\bigm| & 6 \\
\end{pmatrix}
\xrightarrow{\frac{1}{6}\text{R}_{2}}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 1 &\bigm| & -1 \\
    0 & -6 &\bigm| & 6 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - 5\text{R}_{2}}
\begin{pmatrix}
    1 & 0 &\bigm| & 4 \\
    0 & 1 &\bigm| & -1 \\
    0 & -6 &\bigm| & 6 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + 6\text{R}_{2}}
\begin{pmatrix}
    1 & 0 &\bigm| & 4 \\
    0 & 1 &\bigm| & -1 \\
    0 & 0 &\bigm| & 0 \\
\end{pmatrix}
$
<br><br>
Backward Substitution:<br>
$x = 4 + 0t$<br>
$y = -1 + 0t$ <br>
i.e. x = 4 & y = -1

c) 
$
\begin{pmatrix}
    2 & 3 & -1 &\bigm| & -1 \\
    1 & 0 & 1 &\bigm| & 0 \\
    -1 & 2 & -2 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\frac{1}{2}\text{R}_{1}}
\begin{pmatrix}
    1 & \frac{3}{2} & \frac{-1}{2} &\bigm| & \frac{-1}{2} \\
    1 & 0 & 1 &\bigm| & 0 \\
    -1 & 2 & -2 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{pmatrix}
    1 & \frac{3}{2} & \frac{-1}{2} &\bigm| & \frac{-1}{2} \\
    0 & \frac{-3}{2} & \frac{3}{2} &\bigm| & \frac{1}{2} \\
    -1 & 2 & -2 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{1}}
\begin{pmatrix}
    1 & \frac{3}{2} & \frac{-1}{2} &\bigm| & \frac{-1}{2} \\
    0 & \frac{-3}{2} & \frac{3}{2} &\bigm| & \frac{1}{2} \\
    0 & \frac{7}{2} & \frac{-5}{2} &\bigm| & \frac{-1}{2} \\
\end{pmatrix}
\xrightarrow{\frac{-2}{3}\text{R}_{2}}
\begin{pmatrix}
    1 & \frac{3}{2} & \frac{-1}{2} &\bigm| & \frac{-1}{2} \\
    0 & 1 & -1 &\bigm| & \frac{-1}{3} \\
    0 & \frac{7}{2} & \frac{-5}{2} &\bigm| & \frac{-1}{2} \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \frac{7}{2}\text{R}_{2}}
\begin{pmatrix}
    1 & \frac{3}{2} & \frac{-1}{2} &\bigm| & \frac{-1}{2} \\
    0 & 1 & -1 &\bigm| & \frac{-1}{3} \\
    0 & 0 & 1 &\bigm| & \frac{-5}{9} \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \frac{3}{2}\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & \frac{1}{3} &\bigm| & \frac{1}{3} \\
    0 & 1 & -1 &\bigm| & \frac{-1}{3} \\
    0 & 0 & 1 &\bigm| & \frac{-5}{9} \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \frac{1}{3}\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & -1 &\bigm| & \frac{-1}{3} \\
    0 & 0 & 1 &\bigm| & \frac{-5}{9} \\
\end{pmatrix}
$

<br><br>
Backward Substitution:<br>
$\boxed{x_1 = 0}$<br>
$\boxed{x_3 = -\frac{5}{9}}$ <br>
$x_2 - x_3 = -\frac{1}{3}$<br>
$x_2 - (-\frac{5}{9}) = -\frac{1}{3}$<br>
$x_2 = -\frac{1}{3} - \frac{5}{9}$<br>
$\boxed{x_2 = -\frac{8}{9}}$

In [71]:
# A - Pythonic Solution #
a = np.array([[1, -1],
              [2, 1]])

b = np.array([0, 3])

a = AddRow(a, 0, 1, -2)

solution = BackwardSubstitution(a, b)

# Print the solution
print("Solution vector a & y:")
print(solution)

Solution vector a & y:
[1. 1.]


In [72]:
# B -  Pythonic Solution #
a = np.array([[1, 5, -1],
              [-1, 1, -5],
              [2, 4, 4]])

print("a (Original)")
print(a,'\n')
a = AddRow(a, 0, 1, 1)
print("a1")
print(a,'\n')
a = AddRow(a, 0, 2, -2)
print("a2")
print(a,'\n')
a = RowScale(a, 1, 1/6)
print("a3")
print(a,'\n')
a = AddRow(a, 1, 0, -5)
print("a4")
print(a,'\n')
a = AddRow(a, 1, 2, 6)
print("a5")
print(a,'\n')

last_entries = []

for row in a:
    last_entry = row[-1]
    last_entries.append(last_entry)

b = np.array(last_entries)

solution = BackwardSubstitution(a, b)

print(solution)

a (Original)
[[ 1  5 -1]
 [-1  1 -5]
 [ 2  4  4]] 

a1
[[ 1.  5. -1.]
 [ 0.  6. -6.]
 [ 2.  4.  4.]] 

a2
[[ 1.  5. -1.]
 [ 0.  6. -6.]
 [ 0. -6.  6.]] 

a3
[[ 1.  5. -1.]
 [ 0.  1. -1.]
 [ 0. -6.  6.]] 

a4
[[ 1.  0.  4.]
 [ 0.  1. -1.]
 [ 0. -6.  6.]] 

a5
[[ 1.  0.  4.]
 [ 0.  1. -1.]
 [ 0.  0.  0.]] 

[ 4. -1.  0.]


In [73]:
# C - Pythonic Solution #
a = np.array([[2, 3, -1, -1],
              [1, 0, 1, 0],
              [-1, 2, -2, 0]])

print("a (Original)")
print(a,'\n')
a = RowScale(a, 0, 1/2)
print("a1")
print(a,'\n')
a = AddRow(a, 0, 1, -1)
print("a2")
print(a,'\n')
a = AddRow(a, 0, 2, 1)
print("a3")
print(a,'\n')
a = RowScale(a, 1, -2/3)
print("a4")
print(a,'\n')
a = AddRow(a, 1, 2, -7/2)
print("a5")
print(a,'\n')

a = AddRow(a, 1, 0, -3/2)
print("a6")
print(a,'\n')

a = AddRow(a, 1, 0, 1/2)
print("a7")
print(a,'\n')


last_entries = []

for row in a:
    last_entry = row[-1]
    last_entries.append(last_entry)

b = np.array(last_entries)

solution = BackwardSubstitution(a, b)

print("Solution to vector a_1, a_2 & a_3:")
print(solution)

a (Original)
[[ 2  3 -1 -1]
 [ 1  0  1  0]
 [-1  2 -2  0]] 

a1
[[ 1.   1.5 -0.5 -0.5]
 [ 1.   0.   1.   0. ]
 [-1.   2.  -2.   0. ]] 

a2
[[ 1.   1.5 -0.5 -0.5]
 [ 0.  -1.5  1.5  0.5]
 [-1.   2.  -2.   0. ]] 

a3
[[ 1.   1.5 -0.5 -0.5]
 [ 0.  -1.5  1.5  0.5]
 [ 0.   3.5 -2.5 -0.5]] 

a4
[[ 1.          1.5        -0.5        -0.5       ]
 [-0.          1.         -1.         -0.33333333]
 [ 0.          3.5        -2.5        -0.5       ]] 

a5
[[ 1.          1.5        -0.5        -0.5       ]
 [-0.          1.         -1.         -0.33333333]
 [ 0.          0.          1.          0.66666667]] 

a6
[[ 1.          0.          1.          0.        ]
 [-0.          1.         -1.         -0.33333333]
 [ 0.          0.          1.          0.66666667]] 

a7
[[ 1.          0.5         0.5        -0.16666667]
 [-0.          1.         -1.         -0.33333333]
 [ 0.          0.          1.          0.66666667]] 

Solution to vector a_1, a_2 & a_3:
[-0.66666667  0.33333333  0.66666667]


4. Provide reasons why the given matrices are either a row echelon, a reduced row echelon, or niether both.<br>
a. <br>
\begin{pmatrix}
   1 & 0 & 1 \\
   0 & 0 & 3 \\
   0 & 1 & 0 \\
\end{pmatrix}<br>
It is not in row-echelon form because the leading entry in R2 eaceeds the bottom-right entry in R1. Furthermore, it does not meet the criteria for reduced row-echelon form (RREF) as it must first be in row-echelon form. additionally, the leading entries are not the sole non-zero entries in their respective columns. <br><br>
b. <br>
\begin{pmatrix}
   7 & 0 & 1 & 0 \\
   0 & 1 & -1 & 4 \\
   0 & 0 & 0 & 0 \\
\end{pmatrix}<br>
It resides in its REF due to the correct placement of leading entries for R1 & R2. The leading entry below R1 also comprises zeros. Nevertheless, it doesn't qualify as its RREF because the leading entry in R1 is not 1. <br><br>
c. <br>
\begin{pmatrix}
   0 & 1 & 3 & 0 \\
   0 & 0 & 0 & 1 \\
\end{pmatrix}<br>
It is not in row-echelon form as the leading entry in the first row is 0, violating the condition that it should be 1. additionally, it is not in reduced row-echelon form because the leading entry in the second row is the only nonzero entry in its column, but the leading entry in the first row is not the only nonzero entry in its column. <br><br>
d. <br>
\begin{pmatrix}
   0 & 0 & 0 \\
   0 & 0 & 0 \\
   0 & 0 & 0 \\
\end{pmatrix}<br>
It is in row-echelon form as it consists of entirely zeroes  <br>
e.
\begin{pmatrix}
   1 & 0 & 3 & -4 & 0 \\
   0 & 0 & 0 & 0 & 0 \\
   0 & 1 & 5 & 0 & 1 \\
\end{pmatrix}<br>
The given matrix is already in a simplified form. This matrix is in row-echelon form with the leading entry in each nonzero row being 1 and occurring to the right of the leading entry of the previous row. .<br><br>
f. <br>
\begin{pmatrix}
   0 & 0 & 1 \\
   0 & 1 & 0 \\
   1 & 0 & 0 \\
\end{pmatrix}<br>
It is in row-echelon form as it satisfies the conditions: all nonzero rows are above any rows of all zeros, the leading entry of each nonzero row occurs to the right of the leading entry of the previous row, and the leading entry in any nonzero row is 1.<br><br>
g. <br>
\begin{pmatrix}
   1 & 2 & 3 \\
   1 & 0 & 0 \\
   0 & 1 & 1 \\
   0 & 0 & 1 \\
\end{pmatrix}<br>
It is in row-echelon form. It satisfies the conditions: all nonzero rows are above any rows of all zeros, the leading entry of each nonzero row occurs to the right of the leading entry of the previous row, and the leading entry in any nonzero row is 1. <br><br>
h. <br>
\begin{pmatrix}
   2 & 1 & 3 & 5 \\
   0 & 0 & 1 & -1 \\
   0 & 0 & 0 & 3 \\
   0 & 0 & 0 & 0 \\
\end{pmatrix}
<br>
It s in row-echelon form. It satisfies the conditions: all nonzero rows are above any rows of all zeros, the leading entry of each nonzero row occurs to the right of the leading entry of the previous row, and the leading entry in any nonzero row is 1.<br><br>
---

5. Solve the following systems of linear equations<br>
a.<br> 
\begin{equation}
x_1+2x_2-3x_3=9 \\
2x_1-x_2-x_3=0 \\
4x_1-x_2+x_3=4 \\
\end{equation}
<br>

$
\begin{pmatrix}
    1 & 2 & -3 &\bigm| & 9 \\
    2 & -1 & -1 &\bigm| & 0 \\
    4 & -1 & 1 &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & 2 & -3 &\bigm| & 9 \\
    0 & -5 & 5 &\bigm| & -18 \\
    4 & -1 & 1 &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 4\text{R}_{1}}
\begin{pmatrix}
    1 & 2 & -3 &\bigm| & 9 \\
    0 & -5 & 5 &\bigm| & -18 \\
    0 & -9 & 13 &\bigm| & -32 \\
\end{pmatrix}
\xrightarrow{-\frac{1}{5}\text{R}_{2}}
\begin{pmatrix}
    1 & 2 & -3 &\bigm| & 9 \\
    0 & 1 & -1 &\bigm| & \frac{18}{5} \\
    0 & -9 & 13 &\bigm| & -32 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 9\text{R}_{2}}
\begin{pmatrix}
    1 & 2 & -3 &\bigm| & 9 \\
    0 & 1 & -1 &\bigm| & \frac{18}{5} \\
    0 & 0 & 4 &\bigm| & -\frac{2}{5} \\
\end{pmatrix} \\
\\
New Equations:\\
= x_1 + 2x_2 - 3x_3 = 9\\
= x_2 - (-x_3) = \frac{18}{5}\\
= 4x_3 = -\frac{2}{5}\\
\\
Backwards Substitution: \\
\frac{4x_3}{4} = \frac{\frac{2}{5}}{4}\\
\boxed{x_3 = \frac{1}{10}}\\
\\
x_2 - (-x_3) = \frac{18}{5}\\
x_2 - (\frac{1}{10}) = \frac{18}{5}\\
x_2 = \frac{18}{5} + \frac{1}{10}\\
\boxed{x_2 = \frac{37}{10}}\\
x_1 + 2x_2 - 3x_3 = 9\\
x_1 + 2(\frac{37}{10}) - 3(\frac{1}{10}) = 9\\
x_1 + \frac{37}{5}) - \frac{3}{10} = 9\\
\boxed{x_1 = \frac{19}{10}}\\
$

In [74]:

# Pythonic Solution #
a = np.array([[1, 2, -3, 9],
              [2, -1, -1, 0],
              [4, -1, 1, 4]])

print("a (Original)")
print(a,'\n')
a = AddRow(a, 0, 1, -2)
print("a1")
print(a,'\n')
a = AddRow(a, 0, 2, -4)
print("a2")
print(a,'\n')
a = RowScale(a, 1, -1/5)
print("a3")
print(a,'\n')
a = AddRow(a, 1, 2, 9)
print("a4")
print(a,'\n')


last_entries = []

for row in a:
    last_entry = row[-1]
    last_entries.append(last_entry)

b = np.array(last_entries)

solution = BackwardSubstitution(a, b)

print("Solution to vectors a1, a2 & a3:")
print(solution)

a (Original)
[[ 1  2 -3  9]
 [ 2 -1 -1  0]
 [ 4 -1  1  4]] 

a1
[[  1.   2.  -3.   9.]
 [  0.  -5.   5. -18.]
 [  4.  -1.   1.   4.]] 

a2
[[  1.   2.  -3.   9.]
 [  0.  -5.   5. -18.]
 [  0.  -9.  13. -32.]] 

a3
[[  1.    2.   -3.    9. ]
 [ -0.    1.   -1.    3.6]
 [  0.   -9.   13.  -32. ]] 

a4
[[ 1.   2.  -3.   9. ]
 [-0.   1.  -1.   3.6]
 [ 0.   0.   4.   0.4]] 

Solution to vectors a1, a2 & a3:
[1.9 3.7 0.1]


<br>b. <br>
\begin{equation}
x+2y= -1 \\
2x+y+z = 1 \\
-x+y-z = -1
\end{equation}

Manual Solution:<br><br>
$
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & -1 \\
    2 & 1 & 1 &\bigm| & 1 \\
    -1 & 1 & -1 &\bigm| & -1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & -1 \\
    0 & -3 & 1 &\bigm| & 3 \\
    -1 & 1 & -1 &\bigm| & -1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{1}}
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & -1 \\
    0 & -3 & 1 &\bigm| & 3 \\
    0 & 3 & -1 &\bigm| & -2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{2}}
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & -1 \\
    0 & -3 & 1 &\bigm| & 3 \\
    0 & 0 & 0 &\bigm| & 1 \\
\end{pmatrix}
$
<br><br>
- L3: 0z = 1 is not possible, therefore there is no solution to this set

In [75]:
# Pythonic Solution #
a = np.array([[1, 2, 0, -1],
              [2, 1, 1, 1],
              [-1, 1, -1, -1]])

print("Original Matrix")
print(a,'\n')
a = AddRow(a, 0, 1, -2)
print("a1")
print(a,'\n')
a = AddRow(a, 0, 2, 1)
print("a2")
print(a,'\n')
a = AddRow(a, 1, 2, 1)
print("a3")
print(a,'\n')


last_entries = []

for row in a:
    last_entry = row[-1]
    last_entries.append(last_entry)

b = np.array(last_entries)

solution = BackwardSubstitution(a, b)

print("Solution")
print(solution)
print("Not possible")

Original Matrix
[[ 1  2  0 -1]
 [ 2  1  1  1]
 [-1  1 -1 -1]] 

a1
[[ 1.  2.  0. -1.]
 [ 0. -3.  1.  3.]
 [-1.  1. -1. -1.]] 

a2
[[ 1.  2.  0. -1.]
 [ 0. -3.  1.  3.]
 [ 0.  3. -1. -2.]] 

a3
[[ 1.  2.  0. -1.]
 [ 0. -3.  1.  3.]
 [ 0.  0.  0.  1.]] 

Solution
[ 1. -1.  0.]
Not possible


c. <br>
\begin{equation}
x_1-3x_2-2x_3=0 \\
-x_1+2x_2+x_3=0 \\
2x_1+4x_2+6x_3=0 \\
\end{equation}
<br>

Manual Solution:<br><br>
$
\begin{pmatrix}
    1 & -3 & -2 &\bigm| & 0 \\
    -1 & 2 & 1 &\bigm| & 0 \\
    2 & 4 & 6 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + \text{R}_{1}}
\begin{pmatrix}
    1 & -3 & -2 &\bigm| & 0 \\
    0 & -1 & -1 &\bigm| & 0 \\
    2 & 4 & 6 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & -3 & -2 &\bigm| & 0 \\
    0 & -1 & -1 &\bigm| & 0 \\
    0 & 10 & 10 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + 10\text{R}_{2}}
\begin{pmatrix}
    1 & -3 & -2 &\bigm| & 0 \\
    0 & -1 & -1 &\bigm| & 0 \\
    0 & 0 & 0 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - 3\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & 1 &\bigm| & 0 \\
    0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 0 &\bigm| & 0 \\
\end{pmatrix}
$
<br><br>
- L3: 0x1 + 0x2 + 0x3 = 0, therefore x3 can have any value.<br>
L2: x2 + x3 = 0 = x2 = -x3<br>
L1: x1 + x3 = 0 = x1 + -x3<br>

In [76]:
# Pythonic Solution #
a = np.array([[1, -3, -2, 0],
              [-1, 2, 1, 0],
              [2, 4, 6, 0]])

print("Original Matrix")
print(a,'\n')
a = AddRow(a, 0, 1, 1)
print("a1")
print(a,'\n')
a = AddRow(a, 0, 2, -2)
print("a2")
print(a,'\n')
a = AddRow(a, 1, 2, 10)
print("a3")
print(a,'\n')
a = AddRow(a, 1, 0, -3)
print("a4")
print(a,'\n')


last_entries = [] #to get the coefficient array for b

for row in a:
    last_entry = row[-1]
    last_entries.append(last_entry)

b = np.array(last_entries)

solution = BackwardSubstitution(a, b)

print("Solution")
print(solution)

Original Matrix
[[ 1 -3 -2  0]
 [-1  2  1  0]
 [ 2  4  6  0]] 

a1
[[ 1. -3. -2.  0.]
 [ 0. -1. -1.  0.]
 [ 2.  4.  6.  0.]] 

a2
[[ 1. -3. -2.  0.]
 [ 0. -1. -1.  0.]
 [ 0. 10. 10.  0.]] 

a3
[[ 1. -3. -2.  0.]
 [ 0. -1. -1.  0.]
 [ 0.  0.  0.  0.]] 

a4
[[ 1.  0.  1.  0.]
 [ 0. -1. -1.  0.]
 [ 0.  0.  0.  0.]] 

Solution
[ 0. -0.  0.]


<br>d. <br>
\begin{equation}
w+a+2y+z=1 \\
w-a-y+z=0 \\
a+y=1 \\
w+a+z=2
\end{equation}
<br>

Manual Solution:<br><br>
$
\begin{align*}
w + a + 2y + z &= 1 \\
w - a - y + z &= 0 \\
a + y &= 1 \\
w + a + z &= 2
\end{align*}\\
$
<br><br>
$
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 1 \\
1 & -1 & -1 & 1 & \big| & 0 \\
0 & 1 & 1 & 0 & \big| & 1 \\
1 & 1 & 0 & 1 & \big| & 2 \\
\end{bmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 1 \\
0 & -2 & -3 & 0 & \big| & -1 \\
0 & 1 & 1 & 0 & \big| & 1 \\
1 & 1 & 0 & 1 & \big| & 2 \\
\end{bmatrix}
\xrightarrow{\text{R}_{3} + 2\text{R}_{2}}
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 1 \\
0 & -2 & -3 & 0 & \big| & -1 \\
0 & 0 & 1 & 0 & \big| & 1 \\
1 & 1 & 0 & 1 & \big| & 2 \\
\end{bmatrix}
\xrightarrow{\text{R}_{4} + \text{R}_{3}}
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 1 \\
0 & -2 & -3 & 0 & \big| & -1 \\
0 & 0 & 1 & 0 & \big| & 1 \\
1 & 1 & -1 & 1 & \big| & 3 \\
\end{bmatrix}
\xrightarrow{-1\text{R}_{3}}
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 1 \\
0 & -2 & -3 & 0 & \big| & -1 \\
0 & 0 & -1 & 0 & \big| & -1 \\
1 & 1 & -1 & 1 & \big| & 3 \\
\end{bmatrix}
\xrightarrow{\text{R}_{2} - 2\text{R}_{3}}
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 1 \\
0 & -2 & 1 & 0 & \big| & 1 \\
0 & 0 & -1 & 0 & \big| & -1 \\
1 & 1 & -1 & 1 & \big| & 3 \\
\end{bmatrix}
\xrightarrow{\text{R}_{1} - \text{R}_{3}}
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 2 \\
0 & -2 & 1 & 0 & \big| & 1 \\
0 & 0 & -1 & 0 & \big| & -1 \\
1 & 1 & -1 & 1 & \big| & 3 \\
\end{bmatrix}
\xrightarrow{\text{R}_{4} - \text{R}_{3}}
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 2 \\
0 & -2 & 1 & 0 & \big| & 1 \\
0 & 0 & -1 & 0 & \big| & -1 \\
1 & 1 & 0 & 1 & \big| & 4 \\
\end{bmatrix}
\xrightarrow{\text{R}_{1} - 2\text{R}_{3}}
\begin{bmatrix}
1 & 1 & 0 & 1 & \big| & 4 \\
0 & -2 & 1 & 0 & \big| & 1 \\
0 & 0 & -1 & 0 & \big| & -1 \\
1 & 1 & 0 & 1 & \big| & 4 \\
\end{bmatrix}
\xrightarrow{-\frac{1}{2}\text{R}_{2}}
\begin{bmatrix}
1 & 1 & 0 & 1 & \big| & 4 \\
0 & 1 & -\frac{1}{2} & 0 & \big| & -\frac{1}{2} \\
0 & 0 & -1 & 0 & \big| & -1 \\
1 & 1 & 0 & 1 & \big| & 4 \\
\end{bmatrix}
\xrightarrow{\text{R}_{1} - \text{R}_{2}}
\begin{bmatrix}
1 & 0 & \frac{1}{2} & 1 & \big| & \frac{9}{2} \\
0 & 1 & -\frac{1}{2} & 0 & \big| & -\frac{1}{2} \\
0 & 0 & -1 & 0 & \big| & -1 \\
1 & 1 & 0 & 1 & \big| & 4 \\
\end{bmatrix}
\xrightarrow{\text{R}_{4} - \text{R}_{1}}
\begin{bmatrix}
1 & 0 & \frac{1}{2} & 1 & \big| & \frac{9}{2} \\
0 & 1 & -\frac{1}{2} & 0 & \big| & -\frac{1}{2} \\
0 & 0 & -1 & 0 & \big| & -1 \\
0 & 0 & 1 & 1 & \big| & 4 \\
\end{bmatrix}
\xrightarrow{\text{R}_{1} - \text{R}_{4}}
\begin{bmatrix}
1 & 0 & 0 & 0 & \big| & 0 \\
0 & 1 & 0 & 0 & \big| & -\frac{1}{2} \\
0 & 0 & -1 & 0 & \big| & -1 \\
0 & 0 & 1 & 1 & \big| & 4 \\
\end{bmatrix}
$

\begin{align*}
w &= 0 \\
a &= -\frac{1}{2} \\
y &= -1 \\
z &= 0 \\
\end{align*}
<br>

In [77]:
# pythonic solution #
a = np.array([[1, 1, 2, 1, 1],
              [1, -1, -1, 1, 0],
              [0, 1, 1, 0, 1],
              [1, 1, 0, 1, 2]])

print("a (Original)")
print(a,'\n')
a = AddRow(a, 0, 1, -1)
print("a1")
print(a,'\n')
a = AddRow(a, 1, 2, 2)
print("a2")
print(a,'\n')
a = AddRow(a, 2, 3, 1)
print("a3")
print(a,'\n')
a = RowScale(a, 2, -1)
print("a4")
print(a,'\n')
a = AddRow(a, 2, 1, -2)
print("a5")
print(a,'\n')
a = AddRow(a, 2, 0, -1)
print("a6")
print(a,'\n')
a = AddRow(a, 2, 3, -1)
print("a7")
print(a,'\n')
a = AddRow(a, 2, 0, -2)
print("a8")
print(a,'\n')
a = RowScale(a, 1, -1/2)
print("a9")
print(a,'\n')
a = AddRow(a, 1, 0, -1)
print("a10")
print(a,'\n')
a = AddRow(a, 0, 3, -1)
print("a11")
print(a,'\n')
a = AddRow(a, 3, 0, -1)
print("a12")
print(a,'\n')


last_entries = [] #to get the coefficient array for b

for row in a:
    last_entry = row[-1]
    last_entries.append(last_entry)

b = np.array(last_entries)

solution = BackwardSubstitution(a, b)

print("Solution to vectors a, y, z, w:")
print(solution)

a (Original)
[[ 1  1  2  1  1]
 [ 1 -1 -1  1  0]
 [ 0  1  1  0  1]
 [ 1  1  0  1  2]] 

a1
[[ 1.  1.  2.  1.  1.]
 [ 0. -2. -3.  0. -1.]
 [ 0.  1.  1.  0.  1.]
 [ 1.  1.  0.  1.  2.]] 

a2
[[ 1.  1.  2.  1.  1.]
 [ 0. -2. -3.  0. -1.]
 [ 0. -3. -5.  0. -1.]
 [ 1.  1.  0.  1.  2.]] 

a3
[[ 1.  1.  2.  1.  1.]
 [ 0. -2. -3.  0. -1.]
 [ 0. -3. -5.  0. -1.]
 [ 1. -2. -5.  1.  1.]] 

a4
[[ 1.  1.  2.  1.  1.]
 [ 0. -2. -3.  0. -1.]
 [-0.  3.  5. -0.  1.]
 [ 1. -2. -5.  1.  1.]] 

a5
[[  1.   1.   2.   1.   1.]
 [  0.  -8. -13.   0.  -3.]
 [ -0.   3.   5.  -0.   1.]
 [  1.  -2.  -5.   1.   1.]] 

a6
[[  1.  -2.  -3.   1.   0.]
 [  0.  -8. -13.   0.  -3.]
 [ -0.   3.   5.  -0.   1.]
 [  1.  -2.  -5.   1.   1.]] 

a7
[[  1.  -2.  -3.   1.   0.]
 [  0.  -8. -13.   0.  -3.]
 [ -0.   3.   5.  -0.   1.]
 [  1.  -5. -10.   1.   0.]] 

a8
[[  1.  -8. -13.   1.  -2.]
 [  0.  -8. -13.   0.  -3.]
 [ -0.   3.   5.  -0.   1.]
 [  1.  -5. -10.   1.   0.]] 

a9
[[  1.   -8.  -13.    1.   -2. ]
 [ -0.    4.

6. Determine if the vectors are linear combinations<br>
a. <br>
 \begin{equation}
    \textbf{v} = \begin{bmatrix} 1 \\ 2 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} -1 \\ 3 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 2 \\ -6 \end{bmatrix}\\
\end{equation}
<br>
Manual Solution:<br>
\[
x \textbf{u}_2 + y \textbf{u}_3 = \textbf{v}
\]
\begin{align*}
-x + 2y &= 1 \\
3x - 6y &= 2
\end{align*}
<br>
$
\begin{bmatrix}
-1 & 2 & | & 1 \\
3 & -6 & | & 2
\end{bmatrix}
\xrightarrow{\text{R}_{2} + 3\text{R}_{1}}
\begin{bmatrix}
-1 & 2 & | & 1 \\
0 & 0 & | & 5
\end{bmatrix}
$

- This system is inconsistent because the last row implies 0 = 5, which is not true. Therefore, vector v is not a linear combination of u2 and u3.
<br><br>

b. <br>
 \begin{equation}
    \textbf{v} = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}\\
\end{equation}
<br>
Manual Solution:
\begin{align*}
x + 0 &= 1 \\
x + y &= 2 \\
0 + y &= 3
\end{align*}

$
\begin{bmatrix}
1 & 0 & | & 1 \\
1 & 1 & | & 2 \\
0 & 1 & | & 3
\end{bmatrix}
\xrightarrow{\text{R}_{2} - \tb. <br>
\begin{equation}
x+2y= -1 \\
2x+y+z = 1 \\
-x+y-z = -1
\end{equation}ext{R}_{1}}
\begin{bmatrix}
1 & 0 & | & 1 \\
0 & 1 & | & 1 \\
0 & 1 & | & 3
\end{bmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{2}}
\begin{bmatrix}
1 & 0 & | & 1 \\
0 & 1 & | & 1 \\
0 & 0 & | & 2
\end{bmatrix}
$
<br>
- x = 1 and y = 1. Therefore, the vector is a linear combination of the vectors given vectors.
<br><br>
c. <br>
 \begin{equation}
    \textbf{v} = \begin{bmatrix} 3 \\ 1 \\ -2 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}\\
\end{equation}
<br>
Manual Solution:

\begin{align*}
x + 0 &= 3 \\
x + y &= 1 \\
0 + y &= -2
\end{align*}
<br>
$
\begin{bmatrix}
1 & 0 & | & 3 \\
1 & 1 & | & 1 \\
0 & 1 & | & -2
\end{bmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{bmatrix}
1 & 0 & | & 3 \\
0 & 1 & | & -2 \\
0 & 1 & | & -2
\end{bmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{2}}
\begin{bmatrix}
1 & 0 & | & 3 \\
0 & 1 & | & -2 \\
0 & 0 & | & 0
\end{bmatrix}
$
<br>
- Vector v can be expressed as a linear combination of u2 and u3, leading to multiple solutions for both x and y.
<br><br>

7. Show that the following vectors are a span: <br>
a.<br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 1 \\ \end{bmatrix}
\begin{bmatrix}1 \\ -1 \\ \end{bmatrix}
\end{pmatrix}
$
<br>

Manual Solution:<br>
$
\begin{bmatrix}
1 & 1 & | & a \\
1 & -1 & | & y
\end{bmatrix}
\xrightarrow{}
\begin{bmatrix}
\begin{array}{cccc|c}
1 & 1 & | & a & (R_1) \\
1 & -1 & | & y & (R_2)
\end{array}
\end{bmatrix}
\xrightarrow{\text{R}_{2} -\text{R}_{1}}
\begin{bmatrix}
\begin{array}{cccc|c}
1 & 1 & | & a & (R_1) \\
0 & -2 & | & y - a & (R_2 - R_1)
\end{array}
\end{bmatrix}
\xrightarrow{\frac{1}{-2}\text{R}_{2}}
\begin{bmatrix}
\begin{array}{cccc|c}
1 & 1 & | & a & (R_1) \\
0 & 1 & | & \frac{y - a}{-2} & \left(\frac{1}{-2}\right)R_2
\end{array}
\end{bmatrix}
$ <br>
- The following vectors are a span.
<br><br>

b.<br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 0 \\ 1\end{bmatrix}
\begin{bmatrix}1 \\ 1 \\ 0\end{bmatrix}
\begin{bmatrix}0 \\ 1 \\ 1\end{bmatrix}
\end{pmatrix}
$
<br>

Manual Solution: <br>
\begin{align*}
a + b &= a \\
b + c &= y \\
a + c &= z
\end{align*}
$
\begin{bmatrix}
1 & 1 & 0 & | & a \\
0 & 1 & 1 & | & y \\
1 & 0 & 1 & | & z
\end{bmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{1}}
\begin{bmatrix}
1 & 1 & 0 & | & a \\
0 & 1 & 1 & | & y \\
0 & -1 & 1 & | & z - a
\end{bmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{2}}
\begin{bmatrix}
1 & 1 & 0 & | & a \\
0 & 1 & 1 & | & y \\
0 & 0 & 2 & | & y - a + z
\end{bmatrix}
$
<br>
- Span
<br><br>

## c. *Same given as B*<br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 0 \\ 1\end{bmatrix}
\begin{bmatrix}1 \\ 1 \\ 0\end{bmatrix}
\begin{bmatrix}0 \\ 1 \\ 1\end{bmatrix}
\end{pmatrix}
$
<br><br>

Manual Solution: <br>
\begin{align*}
a + b &= a \\
b + c &= y \\
a + c &= z
\end{align*}
$
\begin{bmatrix}
1 & 1 & 0 & | & a \\
0 & 1 & 1 & | & y \\
1 & 0 & 1 & | & z
\end{bmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{1}}
\begin{bmatrix}
1 & 1 & 0 & | & a \\
0 & 1 & 1 & | & y \\
0 & -1 & 1 & | & z - a
\end{bmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{2}}
\begin{bmatrix}
1 & 1 & 0 & | & a \\
0 & 1 & 1 & | & y \\
0 & 0 & 2 & | & y - a + z
\end{bmatrix}
$
<br>
- Span
<br><br>

8. Show that the following vectors are linearly independent:<br>
a. <br>
\begin{equation}
\begin{bmatrix} 3 \\ -1 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} -1 \\ 2 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} 1 \\ 1 \\ 3 \\ 1 \end{bmatrix}
\begin{bmatrix} -1 \\ -1 \\ 1 \\ 3 \end{bmatrix}
\end{equation}<br>
Linearly independent by condition 3 & 4.<br>
b. <br>
\begin{equation}
\begin{bmatrix} 0 \\ 0 \\ 0 \\ 1 \end{bmatrix}
\begin{bmatrix} 0 \\ 0 \\ 2 \\ 1 \end{bmatrix}
\begin{bmatrix} 0 \\ 3 \\ 2 \\ 1 \end{bmatrix}
\begin{bmatrix} 4 \\ 3 \\ 2 \\ 1 \end{bmatrix}
\end{equation}<br>
- m = 4 & n = 4.<br>
L1: 4z = 0; z = 0.<br>
L2: 3w + 3z; w = 0.<br>
L3: 2y + 2w + 2z = 0; y = 0.<br>
L4: a + 0 + 0 + 0 = 0; a = 0.<br>
Linearly independent by condition 1.<br>
c. <br>
\begin{equation}
\begin{bmatrix} 1 \\ -1 \\ 1 \\ 0 \end{bmatrix}
\begin{bmatrix} -1 \\ 1 \\ 0 \\ 1 \end{bmatrix}
\begin{bmatrix} 1 \\ 0 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} 0 \\ 1 \\ -1 \\ 1 \end{bmatrix}
\end{equation}<br>
Linearly independent by condidtion 4.<br>